[package]
name = "game-common"
homepage.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { version = "0.13.1", features = [] }
hexx = { version = "0.16.1", features = ["serde"] }
