[package]
name = "game-common"
homepage.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { version = "0.13.2", features = [] }
hexx = { version = "0.16.1", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
ron = "0.8.1"

[dev-dependencies]
tempfile = "3.10.1"
pretty_assertions = "1.4.0"
